### ISSUE TITLE
Graph node throws error when procceding subgraph parsing.

### ISSUE THREAD

**Issue by deathwing00000** [onflow/flow-evm-gateway#511] opened 2024-09-04 11:26 UTC
## Instructions

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.

### Problem

After deployment of the Graph node and deployment of the subgraph in the process block scanning this error occurs:

``` indexer-1      | Sep 04 04:49:03.570 WARN Trying again after eth_call RPC call for block #2320931 (55b9ae92fe950cd29c485a4b3e57bcc0008ef523f711396e07e9bb6e3f1b94eb) failed (attempt #10) with result Err(Web3Error(Rpc(Error { code: ServerError(-32000), message: "failed to execute script at height: 213497601, with: invalid height not in available range: 213497601", data: None }))), provider: testnet-rpc-0, sgd: 1, subgraph_id: QmTNrQPkZv16zv5uL7cMhXsabUjfKpGQW346QXmMkKMHaJ, component: SubgraphInstanceManager
indexer-1      | Sep 04 04:49:03.570 ERRO Ethereum node returned an error when calling function "name" of contract "ERC20": RPC error: Error { code: ServerError(-32000), message: "failed to execute script at height: 213497601, with: invalid height not in available range: 213497601", data: None }, sgd: 1, subgraph_id: QmTNrQPkZv16zv5uL7cMhXsabUjfKpGQW346QXmMkKMHaJ, component: SubgraphInstanceManager
indexer-1      | Sep 04 04:49:03.570 INFO Done processing trigger, gas_used: 0, data_source: MorphoBlue, handler: handleCreateMarket, total_ms: 73555, transaction: 0x5cf8…9290, address: 0x5d7d…4bae, signature: CreateMarket(indexed bytes32,(address,address,address,address,uint256)), sgd: 1, subgraph_id: QmTNrQPkZv16zv5uL7cMhXsabUjfKpGQW346QXmMkKMHaJ, component: SubgraphInstanceManager
indexer-1      | Sep 04 04:49:03.570 INFO Possible reorg detected, retrying, error: failed to process trigger: block #2320931 (0x55b9…94eb), transaction 5cf88d62102ad61d932fa83b5091d654ac4c84b8105b615c03059af426279290: error while executing at wasm backtrace:
indexer-1      |     0: 0x5fa5 - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#tryCall
indexer-1      |     1: 0x6397 - <unknown>!src/sdk/token/TokenManager#constructor
indexer-1      |     2: 0xf35c - <unknown>!src/initializers/markets/createMarket
indexer-1      |     3: 0x103b7 - <unknown>!src/morpho-blue/handleCreateMarket: Ethereum node returned an error when calling function "name" of contract "ERC20": RPC error: Error { code: ServerError(-32000), message: "failed to execute script at height: 213497601, with: invalid height not in available range: 213497601", data: None }, block_hash: 0x55b9ae92fe950cd29c485a4b3e57bcc0008ef523f711396e07e9bb6e3f1b94eb, block_number: 2320931, sgd: 1, subgraph_id: QmTNrQPkZv16zv5uL7cMhXsabUjfKpGQW346QXmMkKMHaJ, component: SubgraphInstanceManager
```

Basically subgraph met CreateMarket event and tried to execute handleCreateMarket function, which tried to fetch name from ERC20 contract and failed.

Another example:
![image](https://github.com/user-attachments/assets/87adf80f-3cce-434b-b282-e56a47238ba7)

Pretty the same flow, but with different SC.
  
### Context

We are currently working on front end for the MoreMarkets Protocol and it highly depends on the subgraph and the data it returns. Currently it is the blocker for us and we will appreciate if You could look through it ASAP.

**Comment by sideninja** [comment] 2024-09-04 12:00
The problem you are experiencing above is related to executing data at historic height which is no longer available on testnet. The problem is currently we don't keep a complete history for executing calls, so my question is why do you try to execute the call at historic height? 
FYI we are working on a feature to keep complete history but will take some time. On mainnet this shouldn't be an issue tho.

**Comment by deathwing00000** [comment] 2024-09-04 12:15
>  so my question is why do you try to execute the call at historic height? 

It is executed that way because of Graph node itself works with historic heights and we just tried to use Graph Node and their subgraph as the tool to fetch, analyze and store data that we can get from blockchain via parsing the blocks. Also Subgraphs are creating some sort of charts, so maybe for this it used execution of some method on historic heights.

**Comment by mmsys34** [comment] 2024-09-05 08:09
And occasionally, eth_getBlockByHash returns null when I utilize the testnet public RPC URL.

I have tried this:
`curl --location 'https://testnet.evm.nodes.onflow.org' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc":"2.0",
    "method":"eth_getBlockByHash",
    "params":[
        "0x2584c7ebd7710982d72988842935ef931c589fc81d0c598e39dd67b4d52b32e4", 
        true
    ],
    "id":1
}`

And the result is null:
`
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": null
}
`

**Comment by sher9n** [comment] 2024-09-05 08:11
It's very critical for us to resolve this asap given the launch date of the protocol on testnet. @sideninja and @m-Peter do we have a timeline on how soon this can be fixed?

**Comment by franklywatson** [comment] 2024-09-05 11:18
We're investigating an issue with block processing which came up since the upgrade which is affecting the EVM side also

**Comment by sideninja** [comment] 2024-09-05 11:33
@mmsys34 the get block issue was resolved but we are currently reindexing the network which takes some time, I believe today we should deploy EVM GW with that block issue fix.

About the historic execution, I will take a look whether we can support pre-network-upgrade heights. Will get back to you today.

**Comment by sideninja** [comment] 2024-09-05 13:13
@mmsys34 can you give me more details about the request so I can try to reproduce, so what is the contract address and what is the call you are doing?

**Comment by sideninja** [comment] 2024-09-05 13:26
cc @sher9n @deathwing00000

**Comment by sideninja** [comment] 2024-09-05 13:37
I assume this is the contract? https://evm-testnet.flowscan.io/address/0x5D7de68283A0AFcd5A1411596577CC389CDF4BAE?tab=txs

**Comment by mmsys34** [comment] 2024-09-05 13:46
> @mmsys34 can you give me more details about the request so I can try to reproduce, so what is the contract address, contract source and abi and what is the call you are doing?

We are monitoring 2 contracts:
1st: https://evm-testnet.flowscan.io/address/0x5D7de68283A0AFcd5A1411596577CC389CDF4BAE?tab=contract
2nd: https://evm-testnet.flowscan.io/address/0xb21fa39418F3AbBAE407124896B84980E7149b3e?tab=contract

I am operating the graph node on AWS with the Flow EVM testnet public RPC URL.
However, during the block synchronization process, it gets stuck at the errors I have mentioned.

**Comment by deathwing00000** [comment] 2024-09-05 13:52
> I assume this is the contract? https://evm-testnet.flowscan.io/address/0x5D7de68283A0AFcd5A1411596577CC389CDF4BAE?tab=txs

@sideninja 

Basically in the transaction, that was mentioned in the error, CreateMarket() event was emitted by 0x5D7de68283A0AFcd5A1411596577CC389CDF4BAE.

Subgraph parsed that event and tried to do basic script, part of which is get the name of the ERC20 contract, that was provided in the params of event.

I believe it stucked on execution of view method `name()` on the ERC20 contract with address
0xa2ee7435820cd09c35e54ba19361c35fc423fe23
or
0xfd1a1dc5567519b3f4225268cb6bf943bf8cd9c2

**Comment by deathwing00000** [comment] 2024-09-05 13:55
> > I assume this is the contract? https://evm-testnet.flowscan.io/address/0x5D7de68283A0AFcd5A1411596577CC389CDF4BAE?tab=txs
> 
> @sideninja
> 
> Basically in the [transaction](https://evm-testnet.flowscan.io/tx/0x5cf88d62102ad61d932fa83b5091d654ac4c84b8105b615c03059af426279290), that was mentioned in the error, `CreateMarket()` event was emitted by 0x5D7de68283A0AFcd5A1411596577CC389CDF4BAE.
> 
> Subgraph parsed that event and tried to do basic script, part of which is get the name of the ERC20 contract, that was provided in the params of event.
> 
> I believe it stucked on execution of view method `name()` on the ERC20 contract with address 0xa2ee7435820cd09c35e54ba19361c35fc423fe23 or 0xfd1a1dc5567519b3f4225268cb6bf943bf8cd9c2

**Comment by sideninja** [comment] 2024-09-05 13:58
Thank you... looking into it with @m-Peter

**Comment by m-Peter** [comment] 2024-09-05 14:22
```bash
curl -s -XPOST 'https://testnet.evm.nodes.onflow.org' --header 'Content-Type: application/json' --data-raw '{"jsonrpc":"2.0","id":1,"method":"eth_call","params":[{"from":"0x2690eef879df58b97ec7cf830f7627fb1b51f826","gas":"0x0","gasUsed":"0x79b78","input":"0x8c1358a2000000000000000000000000a2ee7435820cd09c35e54ba19361c35fc423fe23000000000000000000000000fd1a1dc5567519b3f4225268cb6bf943bf8cd9c2000000000000000000000000d7d48a64eb6f2ddf740d3258d2df7b2e7122f01a000000000000000000000000cfc5f61bff3fec063a73038e97bbe883360547e70000000000000000000000000000000000000000000000000b1a2bc2ec500000","to":"0x5d7de68283a0afcd5a1411596577cc389cdf4bae","value":"0x0"},"0x236A23"]}'
```

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32000,
    "message": "failed to execute script at height: 213497601, with: invalid height not in available range: 213497601"
  }
}
```
I was able to find the exact call that produces this error. Now we just have to debug why that happens.

**Comment by m-Peter** [comment] 2024-09-05 15:16
> > This is the exact error message ^
> 
> This error is related with our smart contracts or subgraph code?

Not at all, it has to do with our setup, so worry not.

**Comment by sideninja** [comment] 2024-09-05 15:28
We are experiencing an issue where the script is executed in the wrong place. We are looking into as to why and will get back asap.

**Comment by sher9n** [comment] 2024-09-06 07:58
HI @sideninja, do we have an update on this?

**Comment by sideninja** [comment] 2024-09-06 09:27
@sher9n @mmsys34 the blocks should be now available. The call failing will likely need reconfiguring of AN to try again. @peterargue can we increase the compute limit on the AN `access-002.devnet51` to see if this will allow the execution on the AN. What is weird tho, is that this request shouldn't be computationally intensive so not sure why it gets forwarded to EN instead of AN. This is similar to what we see on mainnet, but for this case they just read name of a contract. We will try to figure out how much compute it does use to confirm this. But can we try increase the limit to see if this is resolved.

**Comment by deathwing00000** [comment] 2024-09-06 12:33
> @sher9n @mmsys34 the blocks should be now available. The call failing will likely need reconfiguring of AN to try again. @peterargue can we increase the compute limit on the AN `access-002.devnet51` to see if this will allow the execution on the AN. What is weird tho, is that this request shouldn't be computationally intensive so not sure why it gets forwarded to EN instead of AN. This is similar to what we see on mainnet, but for this case they just read name of a contract. We will try to figure out how much compute it does use to confirm this. But can we try increase the limit to see if this is resolved.

Still meeting pretty the same issue on the same height:
```
indexer-1      | Sep 06 12:29:44.895 INFO Syncing 5 blocks from Ethereum, code: BlockIngestionStatus, blocks_needed: 5, blocks_behind: 5, latest_block_head: 3912349, current_block_head: 3912344, provider: testnet-rpc-0, component: EthereumPollingBlockIngestor
indexer-1      | Sep 06 12:29:46.133 WARN Trying again after eth_call RPC call for block #2320931 (55b9ae92fe950cd29c485a4b3e57bcc0008ef523f711396e07e9bb6e3f1b94eb) failed (attempt #10) with result Err(Web3Error(Rpc(Error { code: ServerError(-32000), message: "failed to execute script at height: 213497601, with: invalid height not in available range: 213497601", data: None }))), provider: testnet-rpc-0, sgd: 1, subgraph_id: QmTNrQPkZv16zv5uL7cMhXsabUjfKpGQW346QXmMkKMHaJ, component: SubgraphInstanceManager
indexer-1      | Sep 06 12:29:46.133 ERRO Ethereum node returned an error when calling function "name" of contract "ERC20": RPC error: Error { code: ServerError(-32000), message: "failed to execute script at height: 213497601, with: invalid height not in available range: 213497601", data: None }, sgd: 1, subgraph_id: QmTNrQPkZv16zv5uL7cMhXsabUjfKpGQW346QXmMkKMHaJ, component: SubgraphInstanceManager
indexer-1      | Sep 06 12:29:46.133 INFO Done processing trigger, gas_used: 0, data_source: MorphoBlue, handler: handleCreateMarket, total_ms: 87150, transaction: 0x5cf8…9290, address: 0x5d7d…4bae, signature: CreateMarket(indexed bytes32,(address,address,address,address,uint256)), sgd: 1, subgraph_id: QmTNrQPkZv16zv5uL7cMhXsabUjfKpGQW346QXmMkKMHaJ, component: SubgraphInstanceManager
indexer-1      | Sep 06 12:29:46.134 INFO Possible reorg detected, retrying, error: failed to process trigger: block #2320931 (0x55b9…94eb), transaction 5cf88d62102ad61d932fa83b5091d654ac4c84b8105b615c03059af426279290: error while executing at wasm backtrace:
indexer-1      |     0: 0x5fa5 - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#tryCall
indexer-1      |     1: 0x6397 - <unknown>!src/sdk/token/TokenManager#constructor
indexer-1      |     2: 0xf35c - <unknown>!src/initializers/markets/createMarket
indexer-1      |     3: 0x103b7 - <unknown>!src/morpho-blue/handleCreateMarket: Ethereum node returned an error when calling function "name" of contract "ERC20": RPC error: Error { code: ServerError(-32000), message: "failed to execute script at height: 213497601, with: invalid height not in available range: 213497601", data: None }, block_hash: 0x55b9ae92fe950cd29c485a4b3e57bcc0008ef523f711396e07e9bb6e3f1b94eb, block_number: 2320931, sgd: 1, subgraph_id: QmTNrQPkZv16zv5uL7cMhXsabUjfKpGQW346QXmMkKMHaJ, component: SubgraphInstanceManager
```

**Comment by sideninja** [comment] 2024-09-06 13:41
@deathwing00000 yes the issue should still be there, we will try to increase limits soon now. I will ping you.

**Comment by sideninja** [comment] 2024-09-06 13:49
@deathwing00000 can you try again?

**Comment by deathwing00000** [comment] 2024-09-06 15:28
@sideninja 
Still getting the same error.

**Comment by mmsys34** [comment] 2024-09-06 16:21
@sideninja 

Sometimes, I am getting this error:
```
2024-09-07 02:17:03 indexer-1   | Sep 06 16:17:03.632 INFO Done processing trigger, gas_used: 0, data_source: MetaMorphoFactory, handler: handleCreateMetaMorpho, total_ms: 0, transaction: 0x53cb…74fb, address: 0xb21f…9b3e, signature: CreateMetaMorpho(indexed address,indexed address,address,uint256,indexed address,string,string,bytes32), sgd: 6, subgraph_id: QmPw1uiXKKuZjnYzSiz11uU8bqnwkAiyYWVDDssKeXDoXu, component: SubgraphInstanceManager
2024-09-07 02:17:03 indexer-1   | Sep 06 16:17:03.633 ERRO Subgraph failed with non-deterministic error: failed to process trigger: block #3430956 (0x12dd…6820), transaction 53cb424df3b079802474c1644baf56e451b36c343d88aeda7fc06d14a32a74fb: module instantiation failed: unknown import: `wasi_snapshot_preview1::fd_write` has not been defined, retry_delay_s: 230, attempt: 1, sgd: 6, subgraph_id: QmPw1uiXKKuZjnYzSiz11uU8bqnwkAiyYWVDDssKeXDoXu, component: SubgraphInstanceManager
```

**Comment by mmsys34** [comment] 2024-09-06 16:47
@sideninja 
I have tested on my local docker container, and got same error.

**Comment by deathwing00000** [comment] 2024-09-09 05:22
@sideninja Is there any update on this?

**Comment by sher9n** [comment] 2024-09-09 16:05
@sideninja and @m-Peter, can you guys please investigate asap. We're aiming for a testnet launch on Friday and will have to delay if this is not resolved. I would really like to avoid that given the FLOW commits.

**Comment by m-Peter** [comment] 2024-09-09 16:10
Hey @sher9n, I am afraid that on my side I cannot do much else. I found the root cause of the problem, but I am not a member of the Flow team, hence I have no access to infra tools etc. I am just a community developer. I think that Gregor is out today, so you'll have to wait for his response on the matter :pray:

**Comment by peterargue** [comment] 2024-09-09 18:09
I took a closer look. The height those scripts use is `213497601`. This is before the last height-coordinated upgrade on testnet, which happened at `214288308 `.

Access nodes are only able to execute scripts against blocks that were produced with a compatible version of FVM. During HCUs, the FVM version is updated, so blocks from before the upgrade can no longer be executed. In that case, they forward the request to an execution node. ENs only have a small amount of history, so the request fails.

I know there is a project in the works that should solve this. @sideninja will have some more info when he's back.

**Comment by deathwing00000** [comment] 2024-09-10 08:28
@peterargue @sideninja 
This script is actually using `213497601` because of the fact that it emitted an event in this block. If we re-deploy the smart contract and redo all the configurations, it should work fine for now. The question is, can we rely on the next HCU not to happen and break everything for us again.... Perhaps you have some opinion on this?

**Comment by sideninja** [comment] 2024-09-10 09:46
We are pushing out a feature on testnet that will completely avoid relying on AN to execute any calls or transactions. This will avoid any issues that you are facing. I'm really sorry for all these troubles.

**Comment by deathwing00000** [comment] 2024-09-10 10:05
@sideninja That sounds really great, thank You a lot! Maybe You have any estimations where it could go live?

**Comment by Extended-UI** [comment] 2024-09-16 10:54
Hey @sideninja, we really need this resolved. Any idea when your fix will go in?

**Comment by sideninja** [comment] 2024-09-16 16:58
It's deployed on testnet but it's taking time to sync up, it's been there since the weekend so I believe tomorrow it should be operational.

**Comment by Extended-UI** [comment] 2024-09-16 17:33
Okay we will check this.

**Comment by sideninja** [comment] 2024-09-17 14:54
I sent a PM grpc API host to the early access node for you to validate.

**Comment by Extended-UI** [comment] 2024-09-17 20:01
Hi @sideninja who did you send the PM to?

**Comment by Extended-UI** [comment] 2024-09-17 20:05
Thanks. I will check this.

**Comment by deathwing00000** [comment] 2024-09-18 12:47
@sideninja 
I've got pretty the same error with grpc that You've provided.

```
indexer-1   | Sep 18 12:45:59.303 INFO Syncing 5 blocks from Ethereum, code: BlockIngestionStatus, blocks_needed: 5, blocks_behind: 5, latest_block_head: 5986643, current_block_head: 5986638, provider: mainnet-rpc-0, component: EthereumPollingBlockIngestor
indexer-1   | Sep 18 12:46:01.618 WARN Trying again after eth_call RPC call for block #5841886 (54c94770addb18ab8f062f51dcf959ae161ad90edb9d17cf98678c7411dab12d) failed (attempt #10) with result Err(Web3Error(Rpc(Error { code: ServerError(-32000), message: "failed to execute script at height: 217018556, with: invalid height not in available range: 217018556", data: None }))), provider: mainnet-rpc-0, sgd: 1, subgraph_id: QmfWeXB4z8vUus3vZx2eEmnykpfNUTgUAdezrLu6bVdYZR, component: SubgraphInstanceManager
indexer-1   | Sep 18 12:46:01.619 ERRO Ethereum node returned an error when calling function "borrowRateView" of contract "IRM": RPC error: Error { code: ServerError(-32000), message: "failed to execute script at height: 217018556, with: invalid height not in available range: 217018556", data: None }, sgd: 1, subgraph_id: QmfWeXB4z8vUus3vZx2eEmnykpfNUTgUAdezrLu6bVdYZR, component: SubgraphInstanceManager
indexer-1   | Sep 18 12:46:01.619 INFO Done processing trigger, gas_used: 0, data_source: MorphoBlue, handler: handleBorrow, total_ms: 90130, transaction: 0xcf15…1c6e, address: 0x9a9b…fafa, signature: Borrow(indexed bytes32,address,indexed address,indexed address,uint256,uint256), sgd: 1, subgraph_id: QmfWeXB4z8vUus3vZx2eEmnykpfNUTgUAdezrLu6bVdYZR, component: SubgraphInstanceManager
indexer-1   | Sep 18 12:46:01.620 INFO Possible reorg detected, retrying, error: failed to process trigger: block #5841886 (0x54c9…b12d), transaction cf15bc2b662352b8ca2795185f8eac999cd49e710675a18ed6fa39bdc4f61c6e: error while executing at wasm backtrace:
indexer-1   |     0: 0xe147 - <unknown>!src/sdk/manager/DataManager#_updateInterestRates
indexer-1   |     1: 0xe5ff - <unknown>!src/sdk/manager/DataManager#updateMarketAndProtocolData
indexer-1   |     2: 0xe8f7 - <unknown>!src/morpho-blue/handleBorrow: Ethereum node returned an error when calling function "borrowRateView" of contract "IRM": RPC error: Error { code: ServerError(-32000), message: "failed to execute script at height: 217018556, with: invalid height not in available range: 217018556", data: None }, block_hash: 0x54c94770addb18ab8f062f51dcf959ae161ad90edb9d17cf98678c7411dab12d, block_number: 5841886, sgd: 1, subgraph_id: QmfWeXB4z8vUus3vZx2eEmnykpfNUTgUAdezrLu6bVdYZR, component: SubgraphInstanceManager
indexer-1   | Sep 18 12:46:01.755 INFO Syncing 5 blocks from Ethereum, code: BlockIngestionStatus, blocks_needed: 5, blocks_behind: 5, latest_block_head: 5986648, current_block_head: 5986643, provider: mainnet-rpc-0, component: EthereumPollingBlockIngestor
```

**Comment by sideninja** [comment] 2024-09-19 10:42
@deathwing00000 let me check

**Comment by sideninja** [comment] 2024-09-19 16:44
@deathwing00000 the issue was the call fails, but the error we return is wrong, it should be:
```
execution reverted: market already created
```

deploying a fix for this now... get back to us tomorrow if things related to this issue work correctly.

**Comment by sideninja** [comment] 2024-09-19 17:22
This should be resolved I believe, but let me know if it behaves as you would like

```
curl -s -XPOST 'https://testnet.evm.nodes.onflow.org' --header 'Content-Type: application/json' --data-raw '{"jsonrpc":"2.0","id":1,"method":"eth_call","params":[{"from":"0x2690eef879df58b97ec7cf830f7627fb1b51f826","gas":"0x79b78","input":"0x8c1358a2000000000000000000000000a2ee7435820cd09c35e54ba19361c35fc423fe23000000000000000000000000fd1a1dc5567519b3f4225268cb6bf943bf8cd9c2000000000000000000000000d7d48a64eb6f2ddf740d3258d2df7b2e7122f01a000000000000000000000000cfc5f61bff3fec063a73038e97bbe883360547e70000000000000000000000000000000000000000000000000b1a2bc2ec500000","to":"0x5d7de68283a0afcd5a1411596577cc389cdf4bae","value":"0x0"},"0x236A23"]}'
{"jsonrpc":"2.0","id":1,"error":{"code":3,"message":"execution reverted: market already created","data":"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000166d61726b657420616c7265616479206372656174656400000000000000000000"}}
```

**Closed** 2024-09-25 10:56 UTC
Labels: Bug

**Comment by deathwing00000** [comment] 2024-10-04 06:57
@sideninja 
Hello, the last fix didn't make it work on testnet and we decided to not use subgraph in this environment. But now we are trying to setup it in mainnet and meeting new issue, but we feel like it can probably have same roots.
Address of ERC20 that probably broke this:
0xd3bf53dac106a0290b0483ecbc89d40fcc961f3e
![photo_2024-10-03_19-37-14](https://github.com/user-attachments/assets/61b58c30-88ec-47b1-b20b-7a72389cc3f6)
```
3: 0x6604 - <unknown>!src/meta-morpho-factory/handleCreateMetaMorpho: Ethereum node returned an error when calling function "name" of contract "ERC20": RPC error: Error { code: ServerError(-32000), message: "invalid: failed transaction: transaction recipient is the zero address", data: None }, block_hash: 0xc7dadbdcead6c3cb9a66ea7d110eaa4316888df691c7a72ac31ed645d1d2e9f9, block_number: 2873583, sgd: 2, subgraph_id: QmY86Z3VALruUatqA86uWTNa9rwjAXCov8pHjdpDCFqecM, component: SubgraphInstanceManager

```
