### ISSUE TITLE
Implement checksum checking

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-evm-gateway#572] opened 2024-09-25 10:05 UTC
The local register index should validate the changes to the state by using the checksum provided by the EN. That is dependent on the PR https://github.com/onflow/flow-go/pull/6456

After each transaction we can produce the checksum and compare that checksum with the checksum we receive from the EN via the transaction executed event. If those checksum match we can be sure the state is correct.

**Comment by j1010001** [comment] 2024-10-16 15:36
Closing, duplicate of https://github.com/onflow/flow-go/issues/6539, implemented in https://github.com/onflow/flow-go/pull/6544, https://github.com/onflow/flow-go/pull/6545, https://github.com/onflow/flow-go/pull/6546

**Closed by j1010001** 2024-10-16 15:36 UTC
